### ISSUE TITLE
Not working with Azure Functions V2 beta

### ISSUE THREAD

**Issue by osamajandali** [yvele/azure-function-express#13]
I have been trying to make this work for a couple of days and I failed.
I saw older closed issues and unfortunately nothing worked.

The way I use it as follows:
1- Create azure locally via (func init, func new)
2- Initialize npm via (npm init)
3- install express and azure-function-express packages
4 - copy paste the basic example (index.js and function.json)
5- start the function via (func start)

**Comment by yvele** [comment]
Do you get an error message? What version of Azure Function runtime are you using?

Are you sure your Azure Function is correctly configured?

**Comment by osamajandali** [comment]
These are the error that I get:
```
Http Functions:

        HttpTriggerJS: http://localhost:7071/api/foo/{bar}/{id}

[3/12/18 8:02:51 PM] Function started (Id=f5dd1017-e52a-4a76-ade6-d33ca8de065f)
[3/12/18 8:02:51 PM] Executing 'Functions.HttpTriggerJS' (Reason='This function was programmatically called via the host APIs.', Id=f5dd1017-e52a-4a76-ade6-d33ca8de065f)
info: Worker.Node.f199c5da-bda2-4eb4-9173-a1c7f4c076c1[0]
      Worker f199c5da-bda2-4eb4-9173-a1c7f4c076c1 malformed message invocationResponse.outputData.data.http.headers: string{k:string} expected
info: Worker.Node.f199c5da-bda2-4eb4-9173-a1c7f4c076c1[0]
      Worker f199c5da-bda2-4eb4-9173-a1c7f4c076c1 uncaught exception:  invocationResponse.outputData.data.http.headers: string{k:string} expected
info: Worker.Node.f199c5da-bda2-4eb4-9173-a1c7f4c076c1[0]
      Worker f199c5da-bda2-4eb4-9173-a1c7f4c076c1 exited with code 1
fail: Worker.Node.f199c5da-bda2-4eb4-9173-a1c7f4c076c1[0]
      Worker encountered an error.
info: Worker.Node.89b39baa-8fe1-4abd-8b4d-f32db67e8c68[0]
      Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.23/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 59742 --workerId 89b39baa-8fe1-4abd-8b4d-f32db67e8c68 --requestId 0ee081f5-5935-4c30-a10d-9876c6147526
[3/12/18 8:02:51 PM] A ScriptHost error has occurred
[3/12/18 8:02:51 PM] Worker process with pid 42308 exited with code 1.
info: Worker.Node.89b39baa-8fe1-4abd-8b4d-f32db67e8c68[0]
      Debugger listening on ws://127.0.0.1:5858/55483461-7eb0-4a4f-829a-1aa9c989bcfc
info: Worker.Node.89b39baa-8fe1-4abd-8b4d-f32db67e8c68[0]
      For help see https://nodejs.org/en/docs/inspector
info: Worker.Node.89b39baa-8fe1-4abd-8b4d-f32db67e8c68[0]
      Worker 89b39baa-8fe1-4abd-8b4d-f32db67e8c68 connecting on 127.0.0.1:59742
```
I use the least version of Azure.
All the config the I do is as mention above, create a new function and copy paste the basic example.
Also I have played with the route as the documentation mentions, but also doesn't seems to work. Maybe I am doing something wrong but I don't know what is it.

**Comment by osamajandali** [comment]
@yvele I feel that I maybe doing something wrong, does this errors make sense to you ?

**Comment by osamajandali** [comment]
Basically, it is the basic example that is provided here in the repo.
The way I did it:
- initial azure function via `func init` then `func new`
- By this I will have working azure function using `func start`
- install `express` and `azure-function-express` via npm
- copy & paste the basic example into `index.js` and `function.js`
- Then finally I did `func start` again.

**Comment by danfsd** [comment]
@osamajandali Have you tried running `func host start` instead of `func start`?

**Comment by erezak** [comment]
@osamajandali Which runtime version are you using?
I can see this working with ~1, but not with beta

**Comment by erezak** [comment]
@yvele Have you seen this behavior with the beta runtime?

**Comment by yvele** [comment]
Unfortunately I'm not using the beta runtime.. did they upgrade the node version?

The express proxy is using internal node properties that are nor public or documented.. They may change between node version.

Can you point me what node version is using the beta runtime?

**Comment by yvele** [comment]
Ok that's definitely the switch from node 6 to 8

**Comment by nevercast** [comment]
There is most certainly a significant change in the http api from node 6 to node 8, so this library is not going to work in beta.

@erezak What I did for our production system is use the legacy Function App 1 runtime, but use babel to shim the async/await stuff. Node 6 has generator functions which can be converted into async with the appropriate transpiler. 

Babel is in a state of crossover at the moment from major version 6 to 7, I've actually started moving my Azure Functions to a webpack pipeline because of cold starts on the consumption plan, but I can spin through my Git history and grab you what you need @erezak if you would like to consider using polyfills for your async stuff and still use the version 1 runtime.

**Comment by murraybauer** [comment]
Running into the same issue, using Beta v2.0 runtime. Could we please have a fix?

Only the Beta v2.0 runtime is cross platform (.Net core), v1.0 is Windows only and I'm on a Mac so can't downgrade.

**Comment by nevercast** [comment]
@murraybauer One option that we opted for at my company is using Vagrant to run a Windows VM for `func`. It's not a pretty setup, but since Beta isn't Production ready it made sense for us, it may or may not for you.

**Comment by yvele** [comment]
Yes! A PR in on the pipe https://github.com/yvele/azure-function-express/pull/18 😉
