### ISSUE TITLE
URL format

### ISSUE THREAD

**Issue by SteveALee** [yvele/azure-function-express#3]
Is it possible to unpack the relationship between the route definition for the function and express mapping?

Where does segments come from?

Can you provide an example URL for invoking you sample route in the README

thanks for this great code

**Comment by yvele** [comment]
@SteveALee Thank you for your words of encouragement 😄 

In [all-routes example](https://github.com/yvele/azure-function-express/tree/master/examples/all-routes), I'm only using `{*segments}` as a glob star to allow express handle all routes itself.

`segments` is not used and could be anything. See [Azure Function documentation](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Http-Functions).

Does that answer your question?

**Comment by SteveALee** [comment]
Yes it does. I did search for any significance so guessed it could be anything. You could add a note where you mentioned it.

Cheers

**Comment by yvele** [comment]
@SteveALee Yep right, I've added an example in README: https://github.com/yvele/azure-function-express/commit/9ac5627352ee01f802534b6049948030f7f3afbe 😉
