### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by olileger** [yvele/azure-function-express#5]
Hi

First of all I need to say you've done a really really great job.
you a star :-)

May I suggest you to add a link to the Azure Functions documentation related to the deployment of npm package ?
[https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version--package-management](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version--package-management)
I believe this make sense and could save few minutes.

Kind Regards

Olivier

**Comment by yvele** [comment]
Ok I've replaced the wiki link with the link specific to the official Node.js documentation
