### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jonschlinkert** [yvele/azure-function-express#7]
Why doesn't this library have any changelogs? This seems really unprofessional and lazy.

**Comment by yvele** [comment]
@jonschlinkert Changelog is in release section https://github.com/yvele/azure-function-express/releases

PS: I should maybe add a `CHANGELOG.md` that mention the release section 😉

**Comment by jonschlinkert** [comment]
Clearly, this was satirical. I guess you don't like it when someone does the same thing you just did on my repo twice? (but not in a satirical way, and I deleted both comments because the issue you trolled was completely unrelated to your comments. Don't troll my issues, and don't assign me work unless you're writing me a check.

**Comment by yvele** [comment]
@jonschlinkert My apologies about that, I wanted to make a little joke (cause you don't have changelog on many repos 😉 ) and that's what happened: On posting, github gave me an error like "Cannot do this task.. blah blah".. I tried on another repo, and again.. error. I thought you did something like blocking. I a really didn't noticed that the messages where in fact posted.. Sorry for the unintentional spam.
