### ISSUE TITLE
Not getting it to work

### ISSUE THREAD

**Issue by paoliniluis** [yvele/azure-function-express#9]
Hey, I've been trying to get this to work without success. 
My index.js:

```js
const createHandler = require("azure-function-express").createHandler;
const express = require("express");
...long lists of require...
const app = express();
app.use(function(req, res, next){
   var data = "";
   req.on('data', function(chunk){ data += chunk})
   req.on('end', function(){
       req.rawBody = data;
       req.body = JSON.parse(data);
       next();
   })
})

app.post("/api/parser",
  ... lists of middlewares...
  (req, res) => {
		res.sendStatus(200)
	}
);
module.exports = createHandler(app);
```

my function.json:

```js
{
  "bindings": [
    {
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "authLevel": "function",
      "methods": [ "post" ],
      "route": "parser"
    },
    {
      "type": "http",
      "name": "res",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

basically a post request to the endpoint starts but never ends... it does not even log the first middleware

**Comment by yvele** [comment]
Ha you tried the [basic sample here](https://github.com/yvele/azure-function-express/tree/master/examples/basic) ?

I've never tried using `"authLevel": "function"`, what is that exactly? What happen if you switch to `"authLevel": "anonymous"`?

PS: And also, why are you not using [expressjs/body-parser](https://github.com/expressjs/body-parser)?

**Comment by skycocker** [comment]
@paoliniluis it might be because of you trying to parse the body yourself -
 https://stackoverflow.com/a/43620157/2113110

**Comment by yvele** [comment]
Yes with Azure Function, the [JSON body is already parsed](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#http-triggers-and-bindings) (and [azure-function-express is only a proxy](https://github.com/yvele/azure-function-express/blob/master/src/IncomingMessage.js#L44) with an express interface)

As @skycocker mentioned, remove the body parsing part of your code and just make uses of `req.body` as a POJO
